p = 60
alert("Bolo de Cenoura")
alert("R$ Cenoura")
c = prompt()
c = parseInt(c)
alert("R$ Ovos")
o = prompt()
o = parseInt(o)
alert("R$ Farinha de Trigo")
ft = prompt()
ft = parseInt(ft)
alert("R$ Fermento")
f = prompt()
f = parseInt(f)
alert("R$ Leite")
l = prompt()
l = parseInt(l)
bolo = (c)
bolo = (o)
bolo = (ft)
bolo = (f)
bolo = (l)
soma = ((c+o+ft+f+l)*60)/100
alert("Porcentagem a ser cobrada " + soma)